=== SamuelCHICHA/RT805/part_2/main/schema_db.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ride_offers" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ride_offer" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="driver_id" type="xs:integer" />
                                        <xs:element name="passengers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="passenger_id" type="xs:integer" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="id" type="xs:integer" />
                                        <xs:element name="start_point" type="xs:string" />
                                        <xs:element name="end_point" type="xs:string" />
                                        <xs:element name="start_date" type="xs:dateTime" />
                                        <xs:element name="end_date" type="xs:dateTime" />
                                        <xs:element name="nb_seat" type="xs:integer" />
                                        <xs:element name="deletion_date" type="xs:dateTime" nillable="true" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ride_requests" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ride_request" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="passenger_id" type="xs:integer" />
                                        <xs:element name="id" type="xs:integer" />
                                        <xs:element name="start_point" type="xs:string" />
                                        <xs:element name="end_point" type="xs:string" />
                                        <xs:element name="start_date" type="xs:dateTime" />
                                        <xs:element name="end_date" type="xs:dateTime" />
                                        <xs:element name="deletion_date" type="xs:dateTime" nillable="true" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="users" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:integer" />
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="lastname" type="xs:string" />
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="password" type="xs:string" />
                                        <xs:element name="is_admin" type="xs:boolean" />
                                        <xs:element name="deletion_date" type="xs:dateTime" nillable="true" minOccurs="0" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SamuelCHICHA/RT805/part_2/main/db_copy.xml
<?xml version="1.0" encoding="UTF-8"?><database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema_db.xsd">
  <ride_offers>
    <ride_offer>
      <driver_id>1</driver_id>
      <passengers/>
      <id>1</id>
      <start_point>Paris</start_point>
      <end_point>Reims</end_point>
      <start_date>1996-11-08T09:00:00</start_date>
      <end_date>2023-05-24T00:00:00</end_date>
      <nb_seat>4</nb_seat>
    </ride_offer>
    <ride_offer>
      <driver_id>1</driver_id>
      <passengers/>
      <id>2</id>
      <start_point>Nantes</start_point>
      <end_point>Bordeaux</end_point>
      <start_date>1996-11-08T09:00:00</start_date>
      <end_date>2023-05-24T00:00:00</end_date>
      <nb_seat>2</nb_seat>
    </ride_offer>
  </ride_offers>
  <ride_requests/>
  <users>
    <user>
      <id>1</id>
      <name>samuel</name>
      <lastname>chicha</lastname>
      <email>samuel.chicha@etudiant.univ-reims.fr</email>
      <password>root</password>
      <is_admin>true</is_admin>
    </user>
  </users>
</database>
